In [26]:
#Garcia Sanchez Brandon Fabian - 1951 - Sistemas
import numpy as np
import pandas as pd

In [27]:
clima_p = pd.read_csv(r'C:\Users\HP\Desktop\9no SEMESTRE\ebner\videos\04 MANIPULACION DE DATOS CON PXNDXS\030 ny_precipitaciones.csv')
clima_p.shape

(2000, 13)

In [28]:
clima_p.head()

,STATION,NAME,DATE,MLY-DUTR-NORMAL,MLY-DUTR-STDDEV,MLY-PRCP-25PCTL,MLY-PRCP-50PCTL,MLY-PRCP-75PCTL,MLY-PRCP-AVGNDS-GE001HI,MLY-PRCP-AVGNDS-GE010HI,MLY-PRCP-AVGNDS-GE050HI,MLY-PRCP-AVGNDS-GE100HI,MLY-PRCP-NORMAL
0,USC00301492,"CINCINNATUS, NY US",1,NaN,NaN,2.04,2.48,3.52,16.8,7.8,1.3,0.3,2.80
1,USC00301492,"CINCINNATUS, NY US",3,NaN,NaN,2.52,3.09,3.89,14.0,8.1,2.0,0.5,3.20
2,USC00301492,"CINCINNATUS, NY US",5,NaN,NaN,2.25,3.07,5.00,12.9,8.4,2.3,0.6,3.96
3,USC00301492,"CINCINNATUS, NY US",6,NaN,NaN,3.31,4.45,5.67,14.3,9.3,3.0,0.7,4.51
4,USC00301492,"CINCINNATUS, NY US",7,NaN,NaN,2.98,3.83,4.87,12.8,8.5,3.2,0.9,4.11

In [29]:
clima_t = pd.read_csv(r'C:\Users\HP\Desktop\9no SEMESTRE\ebner\videos\04 MANIPULACION DE DATOS CON PXNDXS\030 ny_temperaturas.csv')
clima_t.shape

(2244, 9)

In [30]:
clima_t.NAME

0                         CINCINNATUS, NY US
1                         CINCINNATUS, NY US
2                         CINCINNATUS, NY US
3                         CINCINNATUS, NY US
4                         CINCINNATUS, NY US
                        ...
2239    MASSENA INTERNATIONAL AIRPORT, NY US
2240    MASSENA INTERNATIONAL AIRPORT, NY US
2241    MASSENA INTERNATIONAL AIRPORT, NY US
2242    MASSENA INTERNATIONAL AIRPORT, NY US
2243    MASSENA INTERNATIONAL AIRPORT, NY US
Name: NAME, Length: 2244, dtype: object

In [31]:
clima_p[clima_p["NAME"] == "ITHACA CORNELL UNIVERSITY, NY US"]

,STATION,NAME,DATE,MLY-DUTR-NORMAL,MLY-DUTR-STDDEV,MLY-PRCP-25PCTL,MLY-PRCP-50PCTL,MLY-PRCP-75PCTL,MLY-PRCP-AVGNDS-GE001HI,MLY-PRCP-AVGNDS-GE010HI,MLY-PRCP-AVGNDS-GE050HI,MLY-PRCP-AVGNDS-GE100HI,MLY-PRCP-NORMAL
819,USC00304174,"ITHACA CORNELL UNIVERSITY, NY US",1,15.9,1.8,1.15,1.90,2.76,15.8,5.8,0.7,0.1,2.08
820,USC00304174,"ITHACA CORNELL UNIVERSITY, NY US",3,19.0,1.9,2.08,2.37,3.16,13.8,6.2,1.4,0.3,2.64
821,USC00304174,"ITHACA CORNELL UNIVERSITY, NY US",6,22.7,2.4,2.89,3.89,4.86,13.8,8.9,2.5,0.7,3.99
822,USC00304174,"ITHACA CORNELL UNIVERSITY, NY US",7,22.1,1.8,2.81,3.40,4.78,12.1,8.1,2.7,0.8,3.83
823,USC00304174,"ITHACA CORNELL UNIVERSITY, NY US",8,22.3,1.7,2.48,3.52,4.37,11.5,7.0,2.5,0.9,3.63
824,USC00304174,"ITHACA CORNELL UNIVERSITY, NY US",9,22.1,2.4,2.43,3.45,4.98,12.0,7.0,2.5,0.8,3.69
825,USC00304174,"ITHACA CORNELL UNIVERSITY, NY US",11,15.8,2.0,2.55,3.00,3.90,14.4,6.7,1.9,0.4,3.16

In [32]:
precip_itaca = clima_p[clima_p["NAME"] == "ITHACA CORNELL UNIVERSITY, NY US"]
precip_itaca.shape

(7, 13)

In [34]:
itaca_inner_merge = pd.merge(precip_itaca, clima_t)
itaca_inner_merge.shape

(7, 19)

In [43]:
itaca_outer_merge = pd.merge(precip_itaca, clima_t, how="outer", on=["STATION","DATE"])
itaca_outer_merge.columns

Index(['STATION', 'NAME_x', 'DATE', 'MLY-DUTR-NORMAL', 'MLY-DUTR-STDDEV',
       'MLY-PRCP-25PCTL', 'MLY-PRCP-50PCTL', 'MLY-PRCP-75PCTL',
       'MLY-PRCP-AVGNDS-GE001HI', 'MLY-PRCP-AVGNDS-GE010HI',
       'MLY-PRCP-AVGNDS-GE050HI', 'MLY-PRCP-AVGNDS-GE100HI', 'MLY-PRCP-NORMAL',
       'NAME_y', 'MLY-TAVG-NORMAL', 'MLY-TAVG-STDDEV', 'MLY-TMAX-NORMAL',
       'MLY-TMAX-STDDEV', 'MLY-TMIN-NORMAL', 'MLY-TMIN-STDDEV'],
      dtype='object')

In [44]:
itaca_outer_merge.shape

(2244, 20)

In [45]:
itaca_left_merge = pd.merge(precip_itaca, clima_t,
                           how="left", on=['STATION','DATE'])
itaca_left_merge.shape

(7, 20)

In [46]:
itaca_right_merge = pd.merge(clima_t, precip_itaca,
                           how="right", on=['STATION','DATE'])
itaca_right_merge.shape

(7, 20)

In [48]:
clima_join = clima_t.join(clima_p, lsuffix = '_left')
clima_join.head()

,STATION_left,NAME_left,DATE_left,MLY-TAVG-NORMAL,MLY-TAVG-STDDEV,MLY-TMAX-NORMAL,MLY-TMAX-STDDEV,MLY-TMIN-NORMAL,MLY-TMIN-STDDEV,STATION,...,MLY-DUTR-NORMAL,MLY-DUTR-STDDEV,MLY-PRCP-25PCTL,MLY-PRCP-50PCTL,MLY-PRCP-75PCTL,MLY-PRCP-AVGNDS-GE001HI,MLY-PRCP-AVGNDS-GE010HI,MLY-PRCP-AVGNDS-GE050HI,MLY-PRCP-AVGNDS-GE100HI,MLY-PRCP-NORMAL
0,USC00301492,"CINCINNATUS, NY US",1,NaN,NaN,NaN,NaN,NaN,NaN,USC00301492,...,NaN,NaN,2.04,2.48,3.52,16.8,7.8,1.3,0.3,2.80
1,USC00301492,"CINCINNATUS, NY US",2,NaN,NaN,NaN,NaN,NaN,NaN,USC00301492,...,NaN,NaN,2.52,3.09,3.89,14.0,8.1,2.0,0.5,3.20
2,USC00301492,"CINCINNATUS, NY US",3,NaN,NaN,NaN,NaN,NaN,NaN,USC00301492,...,NaN,NaN,2.25,3.07,5.00,12.9,8.4,2.3,0.6,3.96
3,USC00301492,"CINCINNATUS, NY US",4,NaN,NaN,NaN,NaN,NaN,NaN,USC00301492,...,NaN,NaN,3.31,4.45,5.67,14.3,9.3,3.0,0.7,4.51
4,USC00301492,"CINCINNATUS, NY US",5,NaN,NaN,NaN,NaN,NaN,NaN,USC00301492,...,NaN,NaN,2.98,3.83,4.87,12.8,8.5,3.2,0.9,4.11

In [49]:
clima_p.set_index(["STATION","DATE"])

                                                  NAME  MLY-DUTR-NORMAL  \
STATION     DATE
USC00301492 1                       CINCINNATUS, NY US              NaN
            3                       CINCINNATUS, NY US              NaN
            5                       CINCINNATUS, NY US              NaN
            6                       CINCINNATUS, NY US              NaN
            7                       CINCINNATUS, NY US              NaN
...                                                ...              ...
USW00094725 8     MASSENA INTERNATIONAL AIRPORT, NY US             22.2
            9     MASSENA INTERNATIONAL AIRPORT, NY US             22.1
            10    MASSENA INTERNATIONAL AIRPORT, NY US             19.8
            11    MASSENA INTERNATIONAL AIRPORT, NY US             16.4
            12    MASSENA INTERNATIONAL AIRPORT, NY US             16.8

                  MLY-DUTR-STDDEV  MLY-PRCP-25PCTL  MLY-PRCP-50PCTL  \
STATION     DATE
USC00301492 1                 NaN             2.04             2.48
            3                 NaN             2.52             3.09
            5                 NaN             2.25             3.07
            6                 NaN             3.31             4.45
            7                 NaN             2.98             3.83
...                           ...              ...              ...
USW00094725 8                 1.6             2.53             3.52
            9                 2.5             2.34             3.30
            10                2.0             1.83             3.22
            11                2.0             2.12             3.07
            12                2.6             1.77             2.26

                  MLY-PRCP-75PCTL  MLY-PRCP-AVGNDS-GE001HI  \
STATION     DATE
USC00301492 1                3.52                     16.8
            3                3.89                     14.0
            5                5.00                     12.9
            6                5.67                     14.3
            7                4.87                     12.8
...                           ...                      ...
USW00094725 8                4.56                     11.1
            9                4.63                     11.7
            10               4.06                     12.3
            11               3.98                     14.2
            12               2.81                     14.6

                  MLY-PRCP-AVGNDS-GE010HI  MLY-PRCP-AVGNDS-GE050HI  \
STATION     DATE
USC00301492 1                         7.8                      1.3
            3                         8.1                      2.0
            5                         8.4                      2.3
            6                         9.3                      3.0
            7                         8.5                      3.2
...                                   ...                      ...
USW00094725 8                         6.6                      2.1
            9                         7.2                      2.3
            10                        7.1                      1.8
            11                        7.6                      1.6
            12                        6.6                      1.2

                  MLY-PRCP-AVGNDS-GE100HI  MLY-PRCP-NORMAL
STATION     DATE
USC00301492 1                         0.3             2.80
            3                         0.5             3.20
            5                         0.6             3.96
            6                         0.7             4.51
            7                         0.9             4.11
...                                   ...              ...
USW00094725 8                         0.8             3.52
            9                         0.8             3.65
            10                        0.7             3.31
            11                        0.4             3.03
            12                        0.2             2.43

[2000 rows x 11 columns]

In [50]:
clima_joined_total = clima_t.join(clima_p.set_index(["STATION","DATE"]),
                                 lsuffix = "_x",
                                 rsuffix = "_y",
                                 on = ["STATION","DATE"],
                                 )
for i in clima_joined_total.columns:
    print(i)

STATION
NAME_x
DATE
MLY-TAVG-NORMAL
MLY-TAVG-STDDEV
MLY-TMAX-NORMAL
MLY-TMAX-STDDEV
MLY-TMIN-NORMAL
MLY-TMIN-STDDEV
NAME_y
MLY-DUTR-NORMAL
MLY-DUTR-STDDEV
MLY-PRCP-25PCTL
MLY-PRCP-50PCTL
MLY-PRCP-75PCTL
MLY-PRCP-AVGNDS-GE001HI
MLY-PRCP-AVGNDS-GE010HI
MLY-PRCP-AVGNDS-GE050HI
MLY-PRCP-AVGNDS-GE100HI
MLY-PRCP-NORMAL

In [51]:
clima_total_outer_concat = pd.concat([clima_t,clima_p], axis = 1)
clima_total_outer_concat.shape

(2244, 22)

In [52]:
clima_total_outer_concat = pd.concat([clima_t,clima_p], axis = 0)
clima_total_outer_concat.shape

(4244, 19)

In [53]:
df_jerar = pd.concat([clima_t,clima_p], keys = ["temp","precip"])
df_jerar

                 STATION                                  NAME  DATE  \
temp   0     USC00301492                    CINCINNATUS, NY US     1
       1     USC00301492                    CINCINNATUS, NY US     2
       2     USC00301492                    CINCINNATUS, NY US     3
       3     USC00301492                    CINCINNATUS, NY US     4
       4     USC00301492                    CINCINNATUS, NY US     5
...                  ...                                   ...   ...
precip 1995  USW00094725  MASSENA INTERNATIONAL AIRPORT, NY US     8
       1996  USW00094725  MASSENA INTERNATIONAL AIRPORT, NY US     9
       1997  USW00094725  MASSENA INTERNATIONAL AIRPORT, NY US    10
       1998  USW00094725  MASSENA INTERNATIONAL AIRPORT, NY US    11
       1999  USW00094725  MASSENA INTERNATIONAL AIRPORT, NY US    12

             MLY-TAVG-NORMAL  MLY-TAVG-STDDEV  MLY-TMAX-NORMAL  \
temp   0                 NaN              NaN              NaN
       1                 NaN              NaN              NaN
       2                 NaN              NaN              NaN
       3                 NaN              NaN              NaN
       4                 NaN              NaN              NaN
...                      ...              ...              ...
precip 1995              NaN              NaN              NaN
       1996              NaN              NaN              NaN
       1997              NaN              NaN              NaN
       1998              NaN              NaN              NaN
       1999              NaN              NaN              NaN

             MLY-TMAX-STDDEV  MLY-TMIN-NORMAL  MLY-TMIN-STDDEV  \
temp   0                 NaN              NaN              NaN
       1                 NaN              NaN              NaN
       2                 NaN              NaN              NaN
       3                 NaN              NaN              NaN
       4                 NaN              NaN              NaN
...                      ...              ...              ...
precip 1995              NaN              NaN              NaN
       1996              NaN              NaN              NaN
       1997              NaN              NaN              NaN
       1998              NaN              NaN              NaN
       1999              NaN              NaN              NaN

             MLY-DUTR-NORMAL  MLY-DUTR-STDDEV  MLY-PRCP-25PCTL  \
temp   0                 NaN              NaN              NaN
       1                 NaN              NaN              NaN
       2                 NaN              NaN              NaN
       3                 NaN              NaN              NaN
       4                 NaN              NaN              NaN
...                      ...              ...              ...
precip 1995             22.2              1.6             2.53
       1996             22.1              2.5             2.34
       1997             19.8              2.0             1.83
       1998             16.4              2.0             2.12
       1999             16.8              2.6             1.77

             MLY-PRCP-50PCTL  MLY-PRCP-75PCTL  MLY-PRCP-AVGNDS-GE001HI  \
temp   0                 NaN              NaN                      NaN
       1                 NaN              NaN                      NaN
       2                 NaN              NaN                      NaN
       3                 NaN              NaN                      NaN
       4                 NaN              NaN                      NaN
...                      ...              ...                      ...
precip 1995             3.52             4.56                     11.1
       1996             3.30             4.63                     11.7
       1997             3.22             4.06                     12.3
       1998             3.07             3.98                     14.2
       1999             2.26             2.81                     14.6

             MLY-PRCP-AVGNDS-GE010HI  MLY-PRCP-AVGNDS-GE050HI  \
temp   0                         NaN                      NaN
       1                         NaN                      NaN
       2                         NaN                      NaN
       3                         NaN                      NaN
       4                         NaN                      NaN
...                              ...                      ...
precip 1995                      6.6                      2.1
       1996                      7.2                      2.3
       1997                      7.1                      1.8
       1998                      7.6                      1.6
       1999                      6.6                      1.2

             MLY-PRCP-AVGNDS-GE100HI  MLY-PRCP-NORMAL
temp   0                         NaN              NaN
       1                         NaN              NaN
       2                         NaN              NaN
       3                         NaN              NaN
       4                         NaN              NaN
...                              ...              ...
precip 1995                      0.8             3.52
       1996                      0.8             3.65
       1997                      0.7             3.31
       1998                      0.4             3.03
       1999                      0.2             2.43

[4244 rows x 19 columns]